### ISSUE TITLE
No such file or directory on finishing training

### ISSUE THREAD

**Issue by stuartspotlight** [sampathweb/insight-clothing-attributes#5]
I've managed to get the network to train on my machine but once it finishes training and tries to save the results I get the error:-

```
Traceback (most recent call last):
  File "/ml_src/build_models.py", line 37, in <module>
    use_gpu=use_gpu)
  File "/ml_src/classifiers.py", line 466, in create_attributes_model
    save_model(model, weights_path)
  File "/ml_src/classifiers.py", line 262, in save_model
    torch.save(model.state_dict(), weights_path)
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 209, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 132, in _with_file_like
    f = open(f, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/ml_src/weights/vgg16-fcn-266-2/category_GT.pth'
```

Is the folder found in the pytorch system files? Do I need to download these weights from somewhere else?
Thanks

**Comment by manikantanallagatla** [comment]
I too have the same issue. Any idea on how to resolve it?

**Comment by manikantanallagatla** [comment]
Got it. Create directory vgg16-fcn-266-2 inside weights folder
